<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard2.1;net8.0;net9.0;net10.0</TargetFrameworks>
    <Description>Project contains all of the models used in TwitchLib.Client.</Description>
  </PropertyGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\TwitchLib.Client.Enums\TwitchLib.Client.Enums.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <!-- This is a punishment for worshiping wrong gods of abstraction -->
    <_Parameter1>TwitchLib.Client</_Parameter1>
    </AssemblyAttribute>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
        <_Parameter1>TwitchLib.Client.Test</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="System.Memory" Version="4.6.3" Condition="$(TargetFramework) == 'netstandard2.0'" />
  </ItemGroup>
	
</Project>
